In [138]:
#pip install sodapy
#pip install seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sodapy import Socrata
import seaborn as sns
from scipy.stats import ttest_ind, chi2_contingency, mannwhitneyu

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind, chi2_contingency, mannwhitneyu
from sklearn.preprocessing import StandardScaler
from statsmodels.stats.weightstats import DescrStatsW

# Load the dataset
url = "path_to_your_dataset.csv"  # Replace with the actual path or URL
df = pd.read_csv(url)

# Data Cleaning
# 1. Missing Values
missing_values = df.isnull().sum()
print("Missing Values:")
print(missing_values)

# 2. Incorrect Values
# Perform necessary checks based on the data

# 3. Values with Improper Formatting
# Check and convert data types if needed
df['start_date'] = pd.to_datetime(df['start_date'])

# 4. General Data Consistency
# Check for logical inconsistencies

# 5. Data Formatting
# No specific actions needed based on the provided data

# 6. Outliers
# Identify and handle outliers
numerical_columns = df.select_dtypes(include=np.number).columns
for column in numerical_columns:
    sns.boxplot(x=df[column])
    plt.show()

# Handling outliers (you may need a more sophisticated method)
outlier_threshold = 3
for column in numerical_columns:
    z_scores = np.abs((df[column] - df[column].mean()) / df[column].std())
    df = df[(z_scores < outlier_threshold)]

# 7. Normalization
# If needed, normalize numerical columns
scaler = StandardScaler()
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

# 8. Transformation
# If necessary, apply transformations (e.g., log transformation)

# 9. Removing Unnecessary Columns
# Remove columns that do not contribute to the analysis
df = df.drop(['unique_id'], axis=1)

# Data Analysis
# 1. Exploratory Data Analysis (EDA)
# Summary statistics
print("Summary Statistics:")
print(df.describe())

# Visualizations (example: histogram)
sns.histplot(df['data_value'], kde=True)
plt.show()

# 2. Hypothesis Testing
# Example: t-test
group1 = df[df['geo_type_name'] == 'UHF34']['data_value']
group2 = df[df['geo_type_name'] == 'UHF42']['data_value']

t_stat, p_value, _ = ttest_ind(group1, group2)
print("t-statistic:", t_stat)
print("p-value:", p_value)

# You can perform additional hypothesis tests based on your research question

# Interpret Results
# Provide interpretations based on the results of data analysis

# Save the cleaned dataset
df.to_csv("cleaned_dataset.csv", index=False)

In [139]:
#pip install sklearn

In [140]:


# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.cityofnewyork.us", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.cityofnewyork.us,
#                  MyAppToken,
#                  username="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("c3uy-2p5r", limit=2500)

# Convert to pandas DataFrame
df = pd.DataFrame.from_records(results)

#print(results_df.head())
print(df['name'].unique())
print(df['measure'].unique())


df.to_csv('nyc_data.csv', index=False)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

['Nitrogen dioxide (NO2)' 'Fine particles (PM 2.5)' 'Ozone (O3)'
 'Asthma emergency department visits due to PM2.5'
 'Annual vehicle miles traveled' 'Asthma hospitalizations due to Ozone'
 'Respiratory hospitalizations due to PM2.5 (age 20+)'
 'Boiler Emissions- Total SO2 Emissions']
['Mean' 'Estimated annual rate (under age 18)' 'million miles'
 'Estimated annual rate (age 18+)' 'Estimated annual rate'
 'Number per km2']

In [141]:

# Data Cleaning
# 1. Missing Values
missing_values = df.isnull().sum()
print("Missing Values:")
print(missing_values)

Missing Values:
unique_id         0
indicator_id      0
name              0
measure           0
measure_info      0
geo_type_name     0
geo_join_id       0
geo_place_name    0
time_period       0
start_date        0
data_value        0
dtype: int64

In [142]:
# 2. Checking dtypes 

df.dtypes

unique_id         object
indicator_id      object
name              object
measure           object
measure_info      object
geo_type_name     object
geo_join_id       object
geo_place_name    object
time_period       object
start_date        object
data_value        object
dtype: object

In [143]:
# 3. Removing unnecessary columns

cols = ['unique_id', 'time_period']
df = df.drop(columns=cols, axis=1)

In [144]:
# 4 Summary statistics 

df.describe

<bound method NDFrame.describe of      indicator_id                     name measure measure_info geo_type_name  \
0             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
1             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
2             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
3             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
4             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
...           ...                      ...     ...          ...           ...
2495          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42
2496          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42
2497          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42
2498          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42
2499          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42

     geo_join_id                      geo_place_name               start_date  \
0            203  Bedford Stuyvesant - Crown Heights  2010-12-01T00:00:00.000
1            203  Bedford Stuyvesant - Crown Heights  2008-12-01T00:00:00.000
2            204                       East New York  2015-01-01T00:00:00.000
3            103                  Fordham - Bronx Pk  2015-01-01T00:00:00.000
4            104                Pelham - Throgs Neck  2008-12-01T00:00:00.000
...          ...                                 ...                      ...
2495         408                             Jamaica  2013-12-01T00:00:00.000
2496         408                             Jamaica  2017-06-01T00:00:00.000
2497         408                             Jamaica  2018-06-01T00:00:00.000
2498         408                             Jamaica  2016-12-01T00:00:00.000
2499         408                             Jamaica  2020-06-01T00:00:00.000

     data_value
0         25.30
1         26.93
2         19.09
3         19.76
4         22.83
...         ...
2495       8.46
2496       8.62
2497       8.25
2498       7.93
2499       6.73

[2500 rows x 9 columns]>

In [145]:
# clean the data 

# a. remove commas 

df.replace(',', '', regex=True, inplace=True)

# b. for the time data

In [146]:
# find unique values of all df columns 

for column in df.columns:
    unique_values = df[column].unique()
    print(f"Unique values in {column}: {unique_values}")

Unique values in indicator_id: ['375' '365' '386' '648' '643' '657' '661' '650' '640']
Unique values in name: ['Nitrogen dioxide (NO2)' 'Fine particles (PM 2.5)' 'Ozone (O3)'
 'Asthma emergency department visits due to PM2.5'
 'Annual vehicle miles traveled' 'Asthma hospitalizations due to Ozone'
 'Respiratory hospitalizations due to PM2.5 (age 20+)'
 'Boiler Emissions- Total SO2 Emissions']
Unique values in measure: ['Mean' 'Estimated annual rate (under age 18)' 'million miles'
 'Estimated annual rate (age 18+)' 'Estimated annual rate'
 'Number per km2']
Unique values in measure_info: ['ppb' 'mcg/m3' 'per 100000 children' 'per km2' 'per 100000 adults'
 'number']
Unique values in geo_type_name: ['UHF34' 'UHF42' 'CD' 'Borough']
Unique values in geo_join_id: ['203' '204' '103' '104' '306308' '206' '106' '209' '210' '410' '201'
 '101' '102' '402' '301' '107' '207' '208' '407' '302' '202' '1' '211'
 '501502' '501' '108' '110' '112' '310' '312' '403' '409' '303' '304'
 '305307' '2' '408' '205' '404406' '414' '5' '401' '105106107' '313' '413'
 '4' '212' '412' '503504' '105' '305' '406' '306' '3' '502' '307' '308'
 '317' '318' '404' '504' '314' '503' '309' '315' '109' '111' '311' '411'
 '316' '405' '309310']
Unique values in geo_place_name: ['Bedford Stuyvesant - Crown Heights' 'East New York' 'Fordham - Bronx Pk'
 'Pelham - Throgs Neck' 'Chelsea-Village' 'Borough Park'
 'High Bridge - Morrisania' 'Bensonhurst - Bay Ridge'
 'Coney Island - Sheepshead Bay' 'Rockaways'
 'Mott Haven and Melrose (CD1)' 'Financial District (CD1)'
 'Greenwich Village and Soho (CD2)' 'Woodside and Sunnyside (CD2)'
 'Greenpoint' 'Kingsbridge - Riverdale' 'Northeast Bronx' 'West Queens'
 'Washington Heights' 'Hunts Point - Mott Haven'
 'East Flatbush - Flatbush' 'Canarsie - Flatlands' 'Southwest Queens'
 'Morrisania and Crotona (CD3)' 'Lower East Side and Chinatown (CD3)'
 'Central Harlem - Morningside Heights' 'Downtown - Heights - Slope'
 'Bronx' 'Williamsburg - Bushwick' 'Northern SI' 'Port Richmond'
 'Upper East Side (CD8)' 'Central Harlem (CD10)'
 'Washington Heights and Inwood (CD12)'
 'Bay Ridge and Dyker Heights (CD10)' 'Borough Park (CD12)'
 'Flushing - Clearview' 'Lower Manhattan' 'Southeast Queens' 'East Harlem'
 'Upper West Side' 'Upper East Side-Gramercy'
 'Hunts Point and Longwood (CD2)' 'Brooklyn' 'Jamaica' 'Sunset Park'
 'Upper West Side (CD7)' 'Bayside Little Neck-Fresh Meadows'
 'Rockaway and Broad Channel (CD14)' 'Staten Island'
 'Long Island City - Astoria' 'South Bronx' 'Coney Island (CD13)'
 'Queens Village (CD13)' 'Queens' 'Throgs Neck and Co-op City (CD10)'
 'Williamsbridge and Baychester (CD12)' 'Jamaica and Hollis (CD12)'
 'Southern SI' 'Crotona -Tremont' 'Clinton and Chelsea (CD4)'
 'Stuyvesant Town and Turtle Bay (CD6)' 'Belmont and East Tremont (CD6)'
 'Riverdale and Fieldston (CD8)' 'Upper East Side' 'Fresh Meadows'
 'Fordham and University Heights (CD5)' 'Midtown (CD5)'
 'Chelsea - Clinton' 'St. George and Stapleton (CD1)' 'Manhattan'
 'South Beach and Willowbrook (CD2)' 'Greenpoint and Williamsburg (CD1)'
 'Highbridge and Concourse (CD4)' 'Gramercy Park - Murray Hill'
 'Greenwich Village - SoHo' 'East Flatbush (CD17)'
 'Flatlands and Canarsie (CD18)' 'Elmhurst and Corona (CD4)'
 'South Ozone Park and Howard Beach (CD10)'
 'Rego Park and Forest Hills (CD6)' 'Hillcrest and Fresh Meadows (CD8)'
 'Park Slope and Carroll Gardens (CD6)'
 'Crown Heights and Prospect Heights (CD8)'
 'Kingsbridge Heights and Bedford (CD7)' 'South Beach - Tottenville'
 'Flatbush and Midwood (CD14)' 'Flushing and Whitestone (CD7)'
 'Bedford Stuyvesant (CD3)' 'Bushwick (CD4)'
 'Tottenville and Great Kills (CD3)' 'Jackson Heights (CD3)'
 'Union Square - Lower East Side' 'Long Island City and Astoria (CD1)'
 'Fort Greene and Brooklyn Heights (CD2)' 'Sheepshead Bay (CD15)'
 'Stapleton - St. George' 'Morningside Heights and Hamilton Heights (CD9)'
 'East Harlem (CD11)' 'Bensonhurst (CD11)'
 'Parkchester and Soundview (CD9)' 'Morris Park and Bronxdale (CD11)'
 'Kew Gardens and Woodhaven (CD9)' 'Bayside and Little Neck (CD11)'
 'South Crown Heights and Lefferts Gardens (CD9)' 'Willowbrook'
 'Brownsville (CD16)' 'East New York and Starrett City (CD5)'
 'Ridgewood and Maspeth (CD5)' 'Sunset Park (CD7)'
 'Ridgewood - Forest Hills' 'Union Square-Lower Manhattan']
Unique values in start_date: ['2010-12-01T00:00:00.000' '2008-12-01T00:00:00.000'
 '2015-01-01T00:00:00.000' '2020-01-01T00:00:00.000'
 '2012-12-01T00:00:00.000' '2014-12-01T00:00:00.000'
 '2021-01-01T00:00:00.000' '2009-06-01T00:00:00.000'
 '2017-01-01T00:00:00.000' '2009-12-01T00:00:00.000'
 '2017-06-01T00:00:00.000' '2018-06-01T00:00:00.000'
 '2018-12-01T00:00:00.000' '2014-06-01T00:00:00.000'
 '2016-12-01T00:00:00.000' '2013-12-01T00:00:00.000'
 '2011-12-01T00:00:00.000' '2020-06-01T00:00:00.000'
 '2015-12-31T00:00:00.000' '2018-01-01T00:00:00.000'
 '2013-06-01T00:00:00.000' '2021-06-01T00:00:00.000'
 '2012-06-01T00:00:00.000' '2017-12-01T00:00:00.000'
 '2019-01-01T00:00:00.000' '2016-06-01T00:00:00.000'
 '2010-06-01T00:00:00.000' '2020-12-01T00:00:00.000'
 '2011-06-01T00:00:00.000' '2015-12-01T00:00:00.000'
 '2015-06-01T00:00:00.000' '2019-06-01T00:00:00.000'
 '2019-12-01T00:00:00.000' '2012-01-02T00:00:00.000'
 '2009-01-01T00:00:00.000' '2016-01-01T00:00:00.000'
 '2005-01-01T00:00:00.000' '2013-01-01T00:00:00.000']
Unique values in data_value: ['25.30' '26.93' '19.09' ... '26.05' '8.99' '9.43']

In [147]:

unique_counts = df.nunique()

# Display the results
print(unique_counts)

indicator_id         9
name                 8
measure              6
measure_info         6
geo_type_name        4
geo_join_id         72
geo_place_name     112
start_date          38
data_value        1535
dtype: int64

In [148]:

df1 = df[df['measure_info'] == 'ppb']
print(df)

     indicator_id                     name measure measure_info geo_type_name  \
0             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
1             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
2             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
3             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
4             375   Nitrogen dioxide (NO2)    Mean          ppb         UHF34
...           ...                      ...     ...          ...           ...
2495          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42
2496          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42
2497          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42
2498          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42
2499          365  Fine particles (PM 2.5)    Mean       mcg/m3         UHF42

     geo_join_id                      geo_place_name               start_date  \
0            203  Bedford Stuyvesant - Crown Heights  2010-12-01T00:00:00.000
1            203  Bedford Stuyvesant - Crown Heights  2008-12-01T00:00:00.000
2            204                       East New York  2015-01-01T00:00:00.000
3            103                  Fordham - Bronx Pk  2015-01-01T00:00:00.000
4            104                Pelham - Throgs Neck  2008-12-01T00:00:00.000
...          ...                                 ...                      ...
2495         408                             Jamaica  2013-12-01T00:00:00.000
2496         408                             Jamaica  2017-06-01T00:00:00.000
2497         408                             Jamaica  2018-06-01T00:00:00.000
2498         408                             Jamaica  2016-12-01T00:00:00.000
2499         408                             Jamaica  2020-06-01T00:00:00.000

     data_value
0         25.30
1         26.93
2         19.09
3         19.76
4         22.83
...         ...
2495       8.46
2496       8.62
2497       8.25
2498       7.93
2499       6.73

[2500 rows x 9 columns]

In [149]:
# unique for df1
for column in df1.columns:
    unique_values = df1[column].unique()
    print(f"Unique values in {column}: {unique_values}")

Unique values in indicator_id: ['375' '386']
Unique values in name: ['Nitrogen dioxide (NO2)' 'Ozone (O3)']
Unique values in measure: ['Mean']
Unique values in measure_info: ['ppb']
Unique values in geo_type_name: ['UHF34' 'UHF42' 'CD' 'Borough']
Unique values in geo_join_id: ['203' '204' '103' '104' '306308' '206' '106' '209' '210' '410' '201'
 '101' '102' '402' '301' '107' '207' '208' '407' '302' '202' '1' '211'
 '501502' '501' '108' '110' '112' '310' '312' '403' '409' '303' '304'
 '305307' '2' '408' '205' '404406' '414' '5' '401' '105106107' '313' '413'
 '4' '212' '412' '503504' '105' '305' '406' '306' '3' '502' '307' '308'
 '317' '318' '504' '109' '111' '311' '411' '309' '316' '404' '314' '503'
 '405' '315' '309310']
Unique values in geo_place_name: ['Bedford Stuyvesant - Crown Heights' 'East New York' 'Fordham - Bronx Pk'
 'Pelham - Throgs Neck' 'Chelsea-Village' 'Borough Park'
 'High Bridge - Morrisania' 'Bensonhurst - Bay Ridge'
 'Coney Island - Sheepshead Bay' 'Rockaways'
 'Mott Haven and Melrose (CD1)' 'Financial District (CD1)'
 'Greenwich Village and Soho (CD2)' 'Woodside and Sunnyside (CD2)'
 'Greenpoint' 'Kingsbridge - Riverdale' 'Northeast Bronx' 'West Queens'
 'Washington Heights' 'Hunts Point - Mott Haven'
 'East Flatbush - Flatbush' 'Canarsie - Flatlands' 'Southwest Queens'
 'Morrisania and Crotona (CD3)' 'Lower East Side and Chinatown (CD3)'
 'Central Harlem - Morningside Heights' 'Downtown - Heights - Slope'
 'Bronx' 'Williamsburg - Bushwick' 'Northern SI' 'Port Richmond'
 'Upper East Side (CD8)' 'Central Harlem (CD10)'
 'Washington Heights and Inwood (CD12)'
 'Bay Ridge and Dyker Heights (CD10)' 'Borough Park (CD12)'
 'Flushing - Clearview' 'Lower Manhattan' 'Southeast Queens' 'East Harlem'
 'Upper West Side' 'Upper East Side-Gramercy'
 'Hunts Point and Longwood (CD2)' 'Brooklyn' 'Jamaica' 'Sunset Park'
 'Upper West Side (CD7)' 'Bayside Little Neck-Fresh Meadows'
 'Rockaway and Broad Channel (CD14)' 'Staten Island'
 'Long Island City - Astoria' 'South Bronx' 'Coney Island (CD13)'
 'Queens Village (CD13)' 'Queens' 'Throgs Neck and Co-op City (CD10)'
 'Williamsbridge and Baychester (CD12)' 'Jamaica and Hollis (CD12)'
 'Southern SI' 'Crotona -Tremont' 'Clinton and Chelsea (CD4)'
 'Stuyvesant Town and Turtle Bay (CD6)' 'Belmont and East Tremont (CD6)'
 'Riverdale and Fieldston (CD8)' 'Upper East Side' 'Fresh Meadows'
 'Fordham and University Heights (CD5)' 'Midtown (CD5)'
 'Chelsea - Clinton' 'St. George and Stapleton (CD1)' 'Manhattan'
 'South Beach and Willowbrook (CD2)' 'Greenpoint and Williamsburg (CD1)'
 'Highbridge and Concourse (CD4)' 'Gramercy Park - Murray Hill'
 'Greenwich Village - SoHo' 'East Flatbush (CD17)'
 'Flatlands and Canarsie (CD18)'
 'South Ozone Park and Howard Beach (CD10)'
 'Rego Park and Forest Hills (CD6)' 'Hillcrest and Fresh Meadows (CD8)'
 'Crown Heights and Prospect Heights (CD8)'
 'Kingsbridge Heights and Bedford (CD7)' 'South Beach - Tottenville'
 'Bedford Stuyvesant (CD3)' 'Fort Greene and Brooklyn Heights (CD2)'
 'Long Island City and Astoria (CD1)' 'Stapleton - St. George'
 'Morningside Heights and Hamilton Heights (CD9)' 'East Harlem (CD11)'
 'Bensonhurst (CD11)' 'Parkchester and Soundview (CD9)'
 'Morris Park and Bronxdale (CD11)' 'Kew Gardens and Woodhaven (CD9)'
 'Bayside and Little Neck (CD11)'
 'South Crown Heights and Lefferts Gardens (CD9)'
 'East New York and Starrett City (CD5)' 'Brownsville (CD16)'
 'Jackson Heights (CD3)' 'Elmhurst and Corona (CD4)' 'Bushwick (CD4)'
 'Sunset Park (CD7)' 'Flatbush and Midwood (CD14)'
 'Flushing and Whitestone (CD7)' 'Tottenville and Great Kills (CD3)'
 'Ridgewood and Maspeth (CD5)' 'Sheepshead Bay (CD15)'
 'Ridgewood - Forest Hills' 'Willowbrook' 'Union Square - Lower East Side'
 'Park Slope and Carroll Gardens (CD6)' 'Union Square-Lower Manhattan']
Unique values in start_date: ['2010-12-01T00:00:00.000' '2008-12-01T00:00:00.000'
 '2015-01-01T00:00:00.000' '2020-01-01T00:00:00.000'
 '2012-12-01T00:00:00.000' '2014-12-01T00:00:00.000'
 '2021-01-01T00:00:00.000' '2009-06-01T00:00:00.000'
 '2017-01-01T00:00:00.000' '2009-12-01T00:00:00.000'
 '2017-06-01T00:00:00.000' '2018-06-01T00:00:00.000'
 '2018-12-01T00:00:00.000' '2014-06-01T00:00:00.000'
 '2016-12-01T00:00:00.000' '2013-12-01T00:00:00.000'
 '2011-12-01T00:00:00.000' '2020-06-01T00:00:00.000'
 '2015-12-31T00:00:00.000' '2018-01-01T00:00:00.000'
 '2013-06-01T00:00:00.000' '2021-06-01T00:00:00.000'
 '2012-06-01T00:00:00.000' '2017-12-01T00:00:00.000'
 '2019-01-01T00:00:00.000' '2016-06-01T00:00:00.000'
 '2010-06-01T00:00:00.000' '2020-12-01T00:00:00.000'
 '2011-06-01T00:00:00.000' '2015-12-01T00:00:00.000'
 '2015-06-01T00:00:00.000' '2019-06-01T00:00:00.000'
 '2019-12-01T00:00:00.000']
Unique values in data_value: ['25.30' '26.93' '19.09' '19.76' '22.83' '16.19' '38.16' '34.96' '30.10'
 '20.23' '23.73' '26.00' '18.04' '28.44' '18.95' '15.22' '25.70' '16.36'
 '11.41' '21.25' '30.40' '21.61' '36.79' '31.63' '29.27' '26.28' '20.21'
 '28.86' '13.39' '11.97' '23.87' '14.14' '26.69' '13.55' '18.32' '15.40'
 '19.11' '16.64' '24.36' '25.56' '18.08' '23.00' '21.54' '18.52' '21.39'
 '26.24' '18.59' '30.92' '22.32' '23.65' '28.23' '19.54' '23.15' '24.69'
 '26.27' '16.37' '11.69' '13.02' '18.97' '14.37' '13.05' '26.48' '25.17'
 '19.80' '18.62' '20.53' '14.81' '27.13' '25.75' '21.27' '17.00' '16.00'
 '13.11' '21.19' '20.55' '25.48' '27.72' '22.69' '16.98' '29.30' '20.37'
 '26.84' '20.14' '29.44' '20.38' '19.48' '16.42' '19.03' '16.92' '23.78'
 '11.47' '9.80' '28.63' '22.20' '15.84' '25.91' '19.45' '11.03' '28.09'
 '23.50' '16.58' '22.95' '30.24' '13.77' '25.04' '26.54' '19.46' '17.63'
 '15.89' '24.02' '27.76' '30.23' '32.21' '23.20' '22.28' '30.26' '24.99'
 '16.12' '21.15' '23.33' '18.58' '18.72' '15.66' '32.10' '35.65' '21.83'
 '35.28' '20.85' '13.62' '13.16' '24.39' '14.97' '10.82' '13.75' '10.26'
 '26.12' '24.86' '24.81' '12.77' '23.86' '18.89' '28.51' '21.12' '14.77'
 '17.94' '25.99' '23.37' '26.21' '20.56' '18.56' '30.54' '27.71' '31.80'
 '19.36' '16.43' '24.22' '24.11' '19.75' '33.62' '28.43' '27.42' '14.40'
 '13.08' '11.98' '12.84' '12.14' '26.68' '14.16' '25.37' '18.87' '18.03'
 '22.67' '19.63' '14.55' '14.15' '13.88' '31.95' '20.87' '25.25' '19.62'
 '16.17' '28.89' '30.21' '23.32' '19.21' '20.22' '16.52' '25.24' '26.29'
 '18.94' '23.64' '23.05' '20.30' '22.78' '18.82' '9.35' '26.18' '16.21'
 '27.47' '14.49' '16.75' '15.38' '18.49' '19.33' '19.92' '12.11' '14.82'
 '31.48' '21.87' '11.34' '10.37' '8.64' '20.47' '25.92' '16.69' '16.03'
 '23.14' '19.04' '21.77' '15.45' '14.76' '25.77' '23.25' '16.63' '23.62'
 '19.16' '21.33' '20.44' '19.26' '15.54' '20.59' '16.48' '18.66' '17.27'
 '20.79' '14.86' '26.39' '14.02' '15.17' '24.12' '22.13' '30.22' '17.87'
 '24.33' '11.77' '13.95' '23.88' '29.29' '22.65' '15.83' '16.77' '18.50'
 '15.59' '23.49' '21.82' '23.80' '26.34' '14.19' '32.92' '26.42' '18.28'
 '25.14' '23.56' '19.72' '16.07' '18.78' '19.35' '29.40' '21.96' '25.23'
 '28.06' '12.34' '10.66' '13.34' '30.47' '20.57' '15.10' '22.70' '14.13'
 '20.31' '15.93' '39.87' '33.16' '22.64' '37.13' '32.14' '18.77' '26.09'
 '34.83' '32.30' '27.38' '20.48' '24.79' '18.26' '23.89' '19.74' '21.76'
 '21.62' '13.79' '17.08' '17.16' '25.18' '20.54' '26.96' '33.65' '15.07'
 '12.52' '13.68' '9.15' '27.50' '24.95' '16.72' '21.99' '31.62' '33.64'
 '15.92' '16.30' '26.77' '16.80' '14.25' '30.87' '28.69' '17.12' '9.18'
 '13.98' '17.64' '15.06' '11.12' '22.93' '22.21' '20.41' '25.60' '21.57'
 '14.92' '13.96' '28.05' '25.72' '14.09' '19.65' '36.08' '42.24' '33.90'
 '30.31' '21.30' '20.69' '15.52' '21.14' '22.24' '16.39' '16.91' '20.60'
 '16.22' '22.80' '13.52' '23.91' '21.43' '22.79' '18.34' '12.78' '24.97'
 '17.24' '17.44' '17.42' '19.07' '29.21' '29.06' '23.76' '16.41' '20.88'
 '24.96' '14.70' '28.88' '18.96' '23.58' '17.46' '12.23' '27.58' '29.95'
 '30.69' '20.72' '24.92' '28.40' '26.65' '18.06' '27.28' '20.98' '16.84'
 '26.50' '19.17' '11.51' '28.90' '15.76' '12.54' '20.26' '8.44' '16.67'
 '32.68' '22.84' '23.83' '20.52' '24.73' '28.98' '11.93' '30.60' '27.48'
 '18.80' '21.21' '16.57' '26.22' '19.00' '22.49' '25.54' '20.97' '18.12'
 '28.32' '16.87' '22.90' '27.00' '28.66' '31.69' '24.91' '14.50' '15.24'
 '13.57' '15.29' '17.23' '28.35' '23.61' '24.62' '23.85' '23.13' '21.40'
 '20.89' '22.38' '21.35' '21.06' '13.19' '21.68' '24.28' '25.93' '21.02'
 '19.90' '13.78' '14.68' '14.27' '10.55' '14.28' '26.47' '22.44' '17.96'
 '26.86' '22.33' '25.52' '16.40' '25.32' '7.81' '15.77' '12.85' '25.94'
 '21.80' '19.10' '20.12' '21.53' '15.44' '14.65' '15.47' '12.99' '13.45'
 '18.41' '21.11' '18.76' '18.48' '11.62' '20.09' '24.41' '32.07' '23.51'
 '15.81' '26.35' '29.42' '11.09' '16.23' '16.29' '10.22' '22.39' '21.67'
 '19.89' '21.29' '17.34' '31.67' '17.07' '25.16' '29.41' '18.46' '27.99'
 '25.81' '31.05' '21.71' '20.25' '17.72' '24.66' '17.92' '20.91' '13.22'
 '11.40' '27.24' '28.42' '27.63' '27.39' '29.70' '17.22' '17.78' '26.19'
 '27.46' '17.82' '21.13' '16.86' '19.50' '21.09' '14.53' '16.05' '11.49'
 '22.40' '27.01' '30.52' '30.19' '39.68' '24.27' '15.05' '26.90' '26.70'
 '20.07' '19.82' '14.26' '16.97' '12.42' '19.68' '15.04' '19.24' '11.20'
 '27.55' '21.26' '17.47' '32.23' '30.82' '18.75' '29.68' '25.96' '18.40'
 '34.50' '15.53' '24.83' '22.12' '19.40' '29.66' '16.26' '16.24' '23.01'
 '32.72' '31.83' '22.41' '26.99' '25.45' '26.26' '24.87' '25.43' '29.76'
 '18.35' '18.16' '22.10' '23.92' '21.51' '14.30' '21.38' '16.02' '25.21'
 '25.00' '25.84' '29.78' '23.39' '22.30' '24.72' '30.28' '31.29' '31.56'
 '24.37' '25.57' '29.00' '23.57' '19.15' '8.11' '7.88' '18.20' '21.31'
 '36.35' '27.27' '22.58' '24.45' '23.47' '25.90' '9.96' '9.81' '6.10'
 '14.00' '30.62' '28.15' '23.77' '7.22' '13.99' '23.42' '23.07' '32.57'
 '24.44' '12.97' '21.28' '24.53' '31.50' '21.16' '21.10' '22.82' '32.51'
 '24.42' '27.11' '15.97' '14.98' '24.13' '14.38' '24.76' '23.17' '12.89'
 '19.58' '17.45' '27.18' '33.61' '28.68' '16.66' '10.04' '28.62' '25.34'
 '21.59' '31.75' '22.96' '25.87' '16.27' '25.35' '13.14' '29.22' '15.13'
 '39.35' '33.98' '25.29' '12.75' '9.24' '20.01' '33.69' '23.55' '20.58'
 '12.55' '18.45' '18.71' '19.23' '27.70' '19.67' '36.38' '20.80' '12.80'
 '22.22' '16.54' '28.70' '20.67' '21.56' '21.92' '26.58' '27.20' '17.65'
 '28.73' '22.60' '15.73' '20.24' '19.22' '21.32' '22.91' '31.10' '15.48'
 '13.71' '26.49' '14.67' '27.51' '15.43' '17.67' '22.89' '18.84' '29.69'
 '13.24' '26.10' '25.67' '23.43' '28.30' '19.01' '11.07' '17.57' '7.33'
 '21.89' '17.51' '44.20' '20.02' '9.70' '8.38' '22.23' '9.27' '10.99'
 '9.08' '13.63' '14.63' '7.97' '12.07' '25.41' '15.36' '10.01' '19.14'
 '13.03' '22.52' '27.75' '25.68' '32.46' '32.98' '24.63' '32.70' '25.58'
 '33.67' '33.27' '33.76' '30.29' '23.98' '18.11' '14.90' '18.65' '19.93'
 '14.69' '13.86' '16.04' '22.54' '17.83' '14.08' '25.95' '29.39' '30.20'
 '27.80' '30.06' '30.96' '19.42' '17.13' '13.82' '15.61' '20.70' '21.24'
 '14.52' '32.71' '32.53' '22.77' '16.49' '14.62' '34.42' '33.72' '34.43'
 '22.45' '43.32' '31.23' '31.87' '31.01' '30.83' '27.36' '30.45' '32.81'
 '33.00' '33.40' '35.18' '30.13' '30.39' '18.05' '10.92' '18.81' '19.41'
 '22.88' '24.24' '25.40' '28.18' '22.26' '32.39' '25.49' '23.16' '16.70'
 '12.81' '20.33' '22.71' '20.00' '31.03' '20.18' '14.56' '17.52' '16.16'
 '22.19' '29.54' '31.98' '32.93' '33.92' '26.94' '31.85' '31.94' '30.02'
 '32.96' '32.35' '31.68' '30.57' '26.14' '24.57' '31.18' '27.77' '30.93'
 '20.86' '24.29' '21.48' '12.43' '10.79' '14.46' '18.67' '13.33' '23.27'
 '32.97' '17.95' '29.53' '24.50' '20.82' '24.04' '21.17' '17.53' '31.16'
 '31.93' '29.73' '8.57' '12.67' '22.76' '21.50' '15.32' '31.72' '16.65'
 '15.94' '20.83' '8.54' '10.52' '4.94' '33.59' '34.29' '33.44' '25.47'
 '30.55' '33.38' '30.70' '33.04' '34.00' '33.81' '33.19' '21.34' '29.71'
 '29.20' '14.20' '13.47' '32.18' '32.24' '32.84' '36.12' '33.52' '32.95'
 '30.16' '28.45' '25.88' '27.07' '19.91' '16.55' '17.80' '9.82' '33.57'
 '33.63' '34.04' '34.34' '32.85' '20.20' '18.09' '31.53' '31.81' '30.34'
 '26.60' '33.33' '32.67' '29.46' '28.36' '25.83' '15.99' '12.68' '12.50'
 '24.01' '28.58' '28.92' '32.12' '30.30' '30.79' '31.43' '9.49' '8.92'
 '32.76' '30.77' '33.30' '28.87' '26.32' '30.46' '23.99' '26.13' '13.43'
 '31.86' '34.15' '16.01' '30.56' '32.83' '33.12' '33.45' '33.70' '20.29'
 '11.13' '14.11' '11.78' '11.26' '32.04' '32.41' '29.84' '27.84' '31.46'
 '31.12' '31.92' '31.91' '33.15' '24.71' '20.16' '25.76' '26.05']

In [150]:
# unique for df2
df2 = df[(df['measure_info'] == 'per 100,000 adults') & (df['measure'] == 'Estimated annual rate')]
print(df2)

Empty DataFrame
Columns: [indicator_id, name, measure, measure_info, geo_type_name, geo_join_id, geo_place_name, start_date, data_value]
Index: []

In [151]:
for column in df2.columns:
    unique_values = df2[column].unique()
    print(f"Unique values in {column}: {unique_values}")

Unique values in indicator_id: []
Unique values in name: []
Unique values in measure: []
Unique values in measure_info: []
Unique values in geo_type_name: []
Unique values in geo_join_id: []
Unique values in geo_place_name: []
Unique values in start_date: []
Unique values in data_value: []

In [153]:
from scipy import stats
import pandas as pd

sample1 = df[df['name'] == 'Nitrogen dioxide (NO2)']['data_value']
sample2 = df[df['name'] == 'Ozone (O3)']['data_value']

sample1 = pd.to_numeric(sample1.replace(',', '', regex=True), errors='coerce')
sample2 = pd.to_numeric(sample2.replace(',', '', regex=True), errors='coerce')

# Drop NaN values
sample1 = sample1.dropna()
sample2 = sample2.dropna()

# Perform t-test
t_statistic, p_value = stats.ttest_ind(sample1, sample2, equal_var=False)

# Print the results
print(f'T-statistic: {t_statistic}')
print(f'P-value: {p_value}')

# Interpret the results
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the means.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference between the means.")

TypeError: unsupported operand type(s) for /: 'str' and 'int'